import type { Metadata } from "next";
import { Gabarito, Inter, IBM_Plex_Serif } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ProfileProvider } from "@/context/ProfileContext";
import { AppProvider } from "@/context/AppContext";
import LayoutWrapper from "@/components/LayoutWrapper";
const gabarito = Gabarito({
  variable: "--font-gabarito",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const ibmPlexSerif = IBM_Plex_Serif({
  variable: "--font-ibm-serif",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "whispr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.variable} ${inter.variable} ${ibmPlexSerif.variable} antialiased select-none`}
      >
        <Toaster position="top-right" />
        <AppProvider>
          <ProfileProvider>
            <LayoutWrapper>{children}</LayoutWrapper>
          </ProfileProvider>
        </AppProvider>
      </body>
    </html>
  );
}
